const $ = (s) => document.querySelector(s);
const canvas = $('#inkCanvas'), stage = $('#stage'), ctx = canvas.getContext('2d');
let tool = 'draw', color = '#3b87bb', size = 3, drawing = false, strokes = [], current = [], slide = 0;
const colors = [{name:'Chalk blue',value:'#3b87bb'}, {name:'Leaf green',value:'#4d8064'}, {name:'Sun yellow',value:'#e3a82d'}, {name:'Berry red',value:'#be5265'}]; let colorIndex=0;
function resizeCanvas(){const r=stage.getBoundingClientRect(), copy=document.createElement('canvas');copy.width=canvas.width;copy.height=canvas.height;copy.getContext('2d').drawImage(canvas,0,0);canvas.width=r.width;canvas.height=r.height;ctx.drawImage(copy,0,0,r.width,r.height); redraw()}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*(canvas.width/r.width),y:(e.clientY-r.top)*(canvas.height/r.height)}}
function drawStroke(s){if(s.points.length<2)return;ctx.save();ctx.strokeStyle=s.color;ctx.lineWidth=s.size;ctx.lineCap='round';ctx.lineJoin='round';ctx.globalCompositeOperation=s.erase?'destination-out':'source-over';ctx.beginPath();s.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.restore()}
function redraw(){ctx.clearRect(0,0,canvas.width,canvas.height);strokes.filter(s=>s.slide===slide).forEach(drawStroke);$('#annotationCount').textContent=`${strokes.filter(s=>s.slide===slide).length} marks`}
canvas.addEventListener('pointerdown',e=>{if(tool==='laser')return; drawing=true;current=[point(e)];canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{const p=point(e);if(tool==='laser'){$('#laserDot').hidden=false;$('#laserDot').style.left=`${p.x}px`;$('#laserDot').style.top=`${p.y}px`;return}if(!drawing)return;current.push(p);redraw();drawStroke({points:current,color,size,erase:tool==='erase'})});
canvas.addEventListener('pointerup',()=>{if(!drawing)return;drawing=false;if(current.length>1)strokes.push({points:current,color,size,erase:tool==='erase',slide});current=[];redraw()});
canvas.addEventListener('pointerleave',()=>{if(tool==='laser')$('#laserDot').hidden=true});
function setTool(next){tool=next;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===next));canvas.style.cursor=next==='laser'?'none':next==='erase'?'cell':'crosshair';$('#laserDot').hidden=next!=='laser'}
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
document.querySelectorAll('.size').forEach(b=>b.onclick=()=>{size=+b.dataset.size;document.querySelectorAll('.size').forEach(x=>x.classList.toggle('active',x===b))});
$('#clearButton').onclick=()=>{if(confirm('Clear annotations from this slide?')){strokes=strokes.filter(s=>s.slide!==slide);redraw()}};
$('#undoButton').onclick=()=>{for(let i=strokes.length-1;i>=0;i--)if(strokes[i].slide===slide){strokes.splice(i,1);break}redraw()};
$('#colorButton').onclick=()=>{colorIndex=(colorIndex+1)%colors.length;color=colors[colorIndex].value;$('#colorName').textContent=colors[colorIndex].name;document.querySelector('.color-button i').style.background=color};
function go(next){slide=Math.max(0,Math.min(2,next));document.querySelectorAll('.slide').forEach((el,i)=>el.hidden=i!==slide);$('#slideIndicator').textContent=`${slide+1} / 3`;redraw()};$('#previousButton').onclick=()=>go(slide-1);$('#nextButton').onclick=()=>go(slide+1);
document.addEventListener('keydown',e=>{if(e.target.isContentEditable)return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){$('#undoButton').click();e.preventDefault()}if(e.key==='ArrowRight')go(slide+1);if(e.key==='ArrowLeft')go(slide-1);if(e.key.toLowerCase()==='d')setTool('draw');if(e.key.toLowerCase()==='l')setTool('laser');if(e.key.toLowerCase()==='e')setTool('erase');if(e.key==='Escape'){$('#laserDot').hidden=true}});
$('#helpButton').onclick=()=>$('#helpDialog').showModal();$('.dialog-close').onclick=()=>$('#helpDialog').close();
$('#cameraButton').onclick=async()=>{const video=$('#camera');try{if(video.srcObject){video.srcObject.getTracks().forEach(t=>t.stop());video.srcObject=null;$('#cameraFrame').classList.remove('live');$('#cameraButton').textContent='Start camera';$('#inputMessage').textContent='Use your mouse or keyboard now. Camera gestures are an optional experimental input.';return}video.srcObject=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});$('#cameraFrame').classList.add('live');$('#cameraButton').textContent='Stop camera';$('#inputMessage').textContent='Camera is live on this device. Gesture recognition is a modular experimental input.'}catch{ $('#inputMessage').textContent='Camera access was not available. Continue with mouse, touch, or keyboard controls.'}};
$('#exportMenuButton').onclick=()=>{$('#exportMenu').hidden=!$('#exportMenu').hidden};
document.addEventListener('click',e=>{if(!e.target.closest('.top-actions'))$('#exportMenu').hidden=true});
async function exportPNG(){const clone=stage.cloneNode(true);clone.querySelector('#inkCanvas')?.remove();clone.querySelector('#laserDot')?.remove();const styles=Array.from(document.styleSheets).flatMap(sheet=>{try{return Array.from(sheet.cssRules).map(rule=>rule.cssText)}catch{return[]}}).join('');const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${canvas.width}" height="${canvas.height}"><style>${styles}</style><foreignObject width="100%" height="100%">${new XMLSerializer().serializeToString(clone)}</foreignObject></svg>`;const img=new Image();img.onload=()=>{const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const o=out.getContext('2d');o.drawImage(img,0,0);o.drawImage(canvas,0,0);const a=document.createElement('a');a.download=`imagine-lesson-slide-${slide+1}.png`;a.href=out.toDataURL('image/png');a.click()};img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)}
document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>{if(b.dataset.export==='png')exportPNG();else{const printStyle=document.createElement('style');printStyle.textContent='@media print{.topbar,.rail,.control-panel,.stage-meta,.slide-nav,footer{display:none!important}.workspace{display:block!important;padding:0!important}.stage{width:100%!important;box-shadow:none!important}.slide[hidden]{display:none!important}}';document.head.append(printStyle);window.addEventListener('afterprint',()=>printStyle.remove(),{once:true});window.print()}$('#exportMenu').hidden=true});
window.addEventListener('resize',resizeCanvas); resizeCanvas();
